### ISSUE TITLE
Print Farsi Character

### ISSUE THREAD

**Issue by MohammadBagherNoorian** [saeed-khalafinejad/Android-Thermal-Bluetooth-Print#2]
hi saeed
how to print in persian ?

**Comment by saeed-khalafinejad** [comment]
Hi Mohammad,
Just pass your Farsi/Arabic text to the prnMng.printStr() method. Also, be sure that the test page of
your printer contains Farsi/Arabic characters. If not then install a font with Farsi/Arabic support on your device based on your printer manual.
